import studentOne from './../../assets/StudentPhotos/student.jpg';
import studentTwo from './../../assets/StudentPhotos/student2.jpg';
import studentThree from './../../assets/StudentPhotos/student3.jpg';
import studentFour from './../../assets/StudentPhotos/student4.jpg';
import studentFive from './../../assets/StudentPhotos/student5.jpg';

export const studentData = [
  {
    image: studentOne,
    id: '001',
    firstName: 'Peter',
    lastName: 'Doe',
    grade: '5',
    attendance: '85%',
    phoneNumber: '555-000-55',
    address: 'Bridge st No.1',
    selectiveLesson: 'Spanish',
    grades: {
      math: 'B+',
      science: 'A-',
      english: 'C+',
      socialStudies: 'A',
      physicalEducation: 'A+',
      visualArts: 'B+',
    },
  },
  {
    image: studentTwo,
    id: '002',
    firstName: 'Peter',
    lastName: 'Doe',
    grade: '5',
    attendance: '65%',
    phoneNumber: '555-000-55',
    address: 'Bridge st No.1',
    selectiveLesson: 'Spanish',
    grades: {
      math: 'B+',
      science: 'A-',
      english: 'C+',
      socialStudies: 'A',
      physicalEducation: 'A+',
      visualArts: 'B+',
    },
  },
  {
    image: studentThree,
    id: '003',
    firstName: 'Mary',
    lastName: 'Wright',
    grade: '5',
    attendance: '80%',
    phoneNumber: '555-0230-55',
    address: 'Bridge st No.1',
    selectiveLesson: 'Spanish',
    grades: {
      math: 'B+',
      science: 'A-',
      english: 'C+',
      socialStudies: 'A',
      physicalEducation: 'A+',
      visualArts: 'B+',
    },
  },
  {
    image: studentFour,
    id: '004',
    firstName: 'Jane',
    lastName: 'Holland',
    grade: '6',
    attendance: '70%',
    phoneNumber: '554-0230-55',
    address: 'Bridge st No.1',
    selectiveLesson: 'Spanish',
    grades: {
      math: 'B+',
      science: 'A-',
      english: 'C+',
      socialStudies: 'A',
      physicalEducation: 'A+',
      visualArts: 'B+',
    },
  },
  {
    image: studentFive,
    id: '005',
    firstName: 'Jane',
    lastName: 'Holland',
    grade: '6',
    attendance: '70%',
    phoneNumber: '554-0230-55',
    address: 'Bridge st No.1',
    selectiveLesson: 'Spanish',
    grades: {
      math: 'B+',
      science: 'A-',
      english: 'C+',
      socialStudies: 'A',
      physicalEducation: 'A+',
      visualArts: 'B+',
    },
  },
];
